apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader-service
  labels:
    app: reader-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: reader-service
  template:
    metadata:
      labels:
        app: reader-service
    spec:
      containers:
      - name: reader-service
        image: reader-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8084
        env:
        - name: DB_HOST
          value: "postgres-db"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: REDIS_HOST
          value: "redis" # Need Redis manifest too if used
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 20
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: reader-service
spec:
  type: NodePort
  selector:
    app: reader-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 30084
