version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins-odsoft
    privileged: true
    user: root
    ports:
      - "8090:8080" # Mapped to 8090 to avoid conflict with genre-service (8081) and others
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Allow Jenkins to run Docker commands
    restart: unless-stopped

volumes:
  jenkins_data:
